# .github/workflows/ui-tests.yml
# deploy to chromatic
 
name: 'Chromatic'
run-name: Publish to Chromatic

on: 
  push:
    paths:
      - 'src/**/*.vue'
      - 'src/**/*.less'
      - 'src/**/*.css'
      - 'src/**/*.scss'
      - 'src/**/*.sass'
jobs:
 chromatic-deployment:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
       with:
         fetch-depth: 0 # Required to retrieve git history
     - name: Install dependencies
       run: npm install
     - name: Publish to Chromatic
       uses: chromaui/action@v1
       with:
         # Grab this from the Chromatic manage page
         projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
