# .github/workflows/ui-tests.yml
# deploy to chromatic
 
name: 'Chromatic PR Deployment'
on:
  pull_request:
    branches:
      - main
    paths: 
      - 'src/**' 

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    env:
        CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        CHROMATIC_SHA: ${{ github.event.pull_request.head.sha }}
        CHROMATIC_BRANCH: ${{ github.event.pull_request.head.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to retrieve git history

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Specify the Node.js version you are using

      - name: Install dependencies
        run: npm install

      - name: Publish to Chromatic (for approval)
        uses: chromaui/action@v1
        with:
          projectToken: ${{ env.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}

  wait-for-chromatic-approval:
    runs-on: ubuntu-latest
    needs: chromatic-deployment
    steps:
      - name: Wait for Chromatic to approve the PR
        run: |
          echo "Waiting for Chromatic approval..."
          # Custom logic to wait for Chromatic approval can be added here
          # This is a placeholder, you need to integrate with Chromatic API

