# .github/workflows/ui-tests.yml
 
# name: 'Storybook Tests'
# run-name: 'Storybook Tests'
# on: 
#   pull_request:
#     branches:
#       - '**'

# jobs:
#  test:
#    timeout-minutes: 60
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: '20.x'
#      - name: Install dependencies
#        run: yarn
#      - name: Install Playwright
#        run: npx playwright install --with-deps
#      - name: Build Storybook
#        run: NODE_OPTIONS=--max-old-space-size=4096 yarn build-storybook --quiet
#      - name: Serve Storybook and run tests
#        run: |
#          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
#            "npx http-server storybook-static --port 6006 --silent" \
#            "npx wait-on tcp:6006 && npm run test-storybook"
